cmaes/cma.py

I introduce the symmetrization of the covariance matrix to improve the stability of eigenvalue decomposition.
This is a common technique in this community (e.g. [this code of pycma](https://github.com/CMA-ES/pycma/blob/30f8c330795251c618ca8f48646f733159d55b37/cma/sampler.py#L343)).

symmetrization of cov

---

.gitignore
README.md
benchmark/speed_problem.py
cmaes/sampler.py

Fix bugs on RDB storage and run benchmarks.
See https://github.com/c-bata/cmaes/pull/10

RDB benchmarks (SQLite 3)

---

benchmark/speed_problem.py
cmaes/cma.py

See https://github.com/c-bata/cmaes/pull/12

Remove random generator from pickle objects

---

.github/workflows/benchmarks.yml
cmaes/cma.py
cmaes/sampler.py
examples/dynamic_search_space.py
examples/optuna_sampler.py
examples/single_dimension.py
tests/test_sampler.py

See https://github.com/c-bata/cmaes/pull/21

Disable when search_space is changed

---

cmaes/sampler.py

See https://github.com/c-bata/cmaes/pull/23

Fix loguniform distribution

---

.github/workflows/examples.yml
cmaes/sampler.py

"step" attribute is added from Optuna v1.3.0.

Support step argument on IntUniformDistribution

---

cmaes/sampler.py

Deprecate CMASampler

---

cmaes/cma.py

ref https://github.com/CyberAgent/cmaes/pull/29

Avoid numerical errors

---

.github/workflows/benchmarks.yml

See https://github.com/CyberAgent/cmaes/pull/34#issuecomment-641341348

Skip benchmark action if repository is forked

---

setup.cfg

Update classifier: production stable

---

setup.cfg

See https://github.com/pypa/setuptools/blob/ba209a15247b9578d565b7491f88dc1142ba29e4/setup.cfg#L48

Set python_requires = >=3.5

---

.github/workflows/benchmarks.yml

Run benchmark only when GCP secrets are available.

---

.github/workflows/benchmarks.yml
benchmark/README.md
benchmark/optuna_solver.py
benchmark/problem_rastrigin.py
benchmark/runner.sh

Add Benchmark for IPOP-CMA-ES

---

.github/workflows/benchmarks.yml

* Use kurobako v0.2.0
* Cache kurobako CLI.

Use actions/cache for kurobako cli

---

.github/workflows/benchmarks.yml

Avoid following error:
```
##[error]Artifact storage quota has been hit. Unable to upload any new artifacts
```

Reduce to upload kurobako image to Artifact

---

.github/workflows/examples.yml
cmaes/_cma.py
examples/ipop_cmaes.py
examples/quadratic_function.py
setup.cfg

numpy v1.19.0 only supports Python 3.6-3.9.
https://github.com/numpy/numpy/releases/tag/v1.19.0

Drop Python 3.5 support

---

setup.cfg

See https://setuptools.readthedocs.io/en/latest/history.html#id141

Remove numpy from setup_requires

---

.github/workflows/benchmarks.yml
.github/workflows/examples.yml
.github/workflows/tests.yml
requirements-bench.txt
requirements-dev.txt
setup.cfg

* Unset version constraints of numpy
* Add requirements-dev.txt and requirements-bench.txt instead of `extra_requires`.

Unset version constraints of numpy and add requirements.

---

cmaes/_cma.py
cmaes/_sepcma.py
tests/test_boundary.py

Raise an AssertionError when mean is an out of bounds.

Validate bounds domain contains mean

---

README.md

I found an inaccurate part of sep-CMA, so I fixed it.

fix sep-CMA description

---

benchmark/problem_himmelblau.py
benchmark/problem_rastrigin.py
benchmark/problem_rosenbrock.py
benchmark/problem_six_hump_camel.py
cmaes/_cma.py
cmaes/_sepcma.py
cmaes/_warm_start.py
examples/bipop_cmaes.py
examples/ipop_cmaes.py
tools/cmaes_visualizer.py
tools/ws_cmaes_visualizer.py

Please refer to https://github.com/CyberAgentAILab/cmaes/issues/111 for the details.
* a8752ae1971745e8df94881a3a7f957fe72e006e: Fix mutable mean
* 47e8429b24a8b514a663f08e572fdabc6c91fb44: Reformat by black

Fix mutable

---

.github/workflows/pypi-publish.yml

Use `gh` like https://github.com/optuna/optuna-dashboard/blob/main/.github/workflows/github-release.yml

Use gh instead of ghr

---

cmaes/_cma.py
cmaes/_cmawm.py
cmaes/_sepcma.py

Add a public method to set rng seeds.
Also, I added the `CMAwM._rng` property for backward compatibility.

Add rng related methods

---

cmaes/_cmawm.py

Refactoring of the `CMAwM` class. Please see each commit for each change.
This PR is intended to keep the original behavior with the same seed.

Refactor `CMAwM`

---

cmaes/_cmawm.py
tests/test_cmawm.py

Follow-up #142
See https://github.com/CyberAgentAILab/cmaes/pull/142#pullrequestreview-1231190994

Add a test case for no discrete spaces.

---

cmaes/__init__.py

Bump the version up to v0.9.1

---

cmaes/__init__.py
cmaes/_dxnesic.py

Implementation of DX-NES-IC, which is a recent variant of natural evolution strategies.
Paper: https://ieeexplore.ieee.org/abstract/document/9504865

add DX-NES-IC

---

cmaes/__init__.py
cmaes/_xnes.py

xNES implementation
paper: https://dl.acm.org/doi/10.1145/1830483.1830557

xNES implementation

---

cmaes/_cma.py

Implementation of learning rate adaptation for CMA-ES.
Paper: https://arxiv.org/abs/2304.03473

add LRA-CMA-ES

---

.github/workflows/examples.yml
.github/workflows/tests.yml
pyproject.toml

* Drop Python 3.7 support
* Add Python 3.12 support

Add support for Python 3.12

---

.github/workflows/tests.yml
benchmark/problem_rastrigin.py

Refs
https://github.com/CyberAgentAILab/cmaes/pull/157

Fix CI failures

---

cmaes/_catcma.py

I found an error in the PR #178 that was merged previously. This PR contains a small fix for that issue.

fix CatCMA

---

cmaes/_catcma.py

I have modified the weight of CatCMA.

fix the weight of CatCMA

---

cmaes/__init__.py

refs https://github.com/CyberAgentAILab/cmaes/pull/184#issuecomment-2285406500

Bump the version up to `v0.11.1`

---

.github/workflows/examples.yml
.github/workflows/pypi-publish.yml
.github/workflows/tests.yml
README.md
pyproject.toml

This PR drops the support for Python 3.7

Update supported Python versions

---

cmaes/__init__.py

Bump up the version to v0.12.0
