.github/workflows/lint.yml
README.md
benchmark/profile.py
benchmark/speed_test.py
cmaes/cma.py
setup.py
tests/test_compress_symmetric.py

After my investigation at https://github.com/c-bata/cmaes/pull/11.
Compressing the covariance matrix makes the size of the pickle serialized CMA object almost half size. But the performance is a bit worse, especially in the low-dimensional search space.
```
import sys
x = {attr: sys.getsizeof(pickle.dumps(getattr(optimizer, attr))) for attr in optimizer.__dict__}
```
```
{'_n_dim': 38, '_popsize': 38, '_mu': 38, '_mu_eff': 151,
'_cc': 151, '_c1': 151, '_cmu': 151, '_c_sigma': 151, '_d_sigma': 151,
'_cm': 38, '_chi_n': 54, '_weights': 302, '_p_sigma': 585, '_pc': 585,
'_mean': 585, '_C': 20187, '_sigma': 151, '_D': 37, '_B': 37, '_bounds': 987,
'_n_max_resampling': 48, '_g': 38, '_rng': 2823}
```
Before
`python benchmark/speed_problem.py --storage sqlite --sampler cmaes --trials 100 …

Reduce the size of pickle serialized object.

---

.github/workflows/examples.yml
cmaes/cma.py
cmaes/sampler.py
examples/quadratic_function.py
setup.py

Add Python 3.5 support to add integration in Optuna.
* Avoid using variable annotation syntax for type hints.
* Avoid using f-string.
* Run Python 3.5 examples on CI.
* See the results of https://github.com/c-bata/cmaes/pull/15

Python 3.5 support.

---

README.md

An optuna sampler based on this library is available from v1.3.0.
https://github.com/optuna/optuna/releases/tag/v1.3.0
https://optuna.readthedocs.io/en/stable/reference/samplers.html#optuna.samplers.CmaEsSampler

Update README for an official Optuna sampler

---

README.md
cmaes/monkeypatch.py
cmaes/sampler.py
examples/monkeypatch.py

Backports of https://github.com/optuna/optuna/pull/885
```python
import optuna
from cmaes.monkeypatch import patch_fast_intersection_search_space
patch_fast_intersection_search_space()
def objective(trial: optuna.Trial):
x1 = trial.suggest_uniform("x1", -4, 4)
x2 = trial.suggest_uniform("x2", -4, 4)
return (x1 - 3) ** 2 + (10 * (x2 + 2)) ** 2
def main():
optuna.logging.set_verbosity(optuna.logging.INFO)
sampler = optuna.samplers.CmaEsSampler()
study = optuna.create_study(sampler=sampler)
study.optimize(objective, n_trials=1000, gc_after_trial=False)
if __name__ == "__main__":
main()
```
**Before (without patch_fast_intersection_search_space)**
0m55.712s
**After (with patch_fast_intersection_search_space)**
0m29.618s

Monkeypatch for faster intersection search space

---

cmaes/cma.py

The current implementation adds the small value (1e-16) to every element of the covariance matrix to prevent eigenvalue decomposition errors.
However, in order to maintain positive definiteness, it is enough to add the small value only to the diagonal components, which is more intuitive.

change to avoid eigendecomposition error

---

cmaes/cma.py

This PR is another solution for addressing the problem in #17.
(And this is also a remake of PR #29.)
changed points
avoid 0 division (Eq.(46) in the CMA-ES tutorial paper)
add small value to eigenvalues
checked
No error occurs for a 2-dimensional sphere function during 100000 iterations.
unchecked
Performance changes for any function.
Parameter tuning for epsilon, which is used for avoiding numerical errors.

avoid numerical error

---

cmaes/cma.py

Fix numerical overflow errors (simplified version of #34).

---

cmaes/cma.py

In the current implementation of `CMA` class, 
- we calculate eigenvalues and vectors by using `numpy.linalg.eigh`, and then take a route for eigenvalues, and
- we take `numpy.exp` each time the `tell` function is called.
For the first, due to the numerical error in `numpy.linalg.eigh`, the eigenvalue may be negative and the result of the root may be Nan. As for the second, `numpy.exp` may overflow when the variance of the objective function is very large. This PR aims to resolve the above problems.
- If an eigenvalue becomes negative due to a numerical error, it is corrected to a small positive number (CMA._epsilon).
- If it is large enough to overflow, replace it with a value that does not overflow.

Avoid numerical errors and overflow.

---

cmaes/_cma.py

While I checked the behavior of #47, I found a bug that `c1 <= 1 - cmu` will be False due to numerical overflow error.

Fix cmu calculation error for large popsize

---

setup.cfg

I bumped development status to `Production Stable` from `Beta` at #43.
Note that #43 is merged after released v0.5.1. So still not published.
https://pypi.org/project/cmaes/0.5.1/
I revert it due to #49 and #50.

Revert development status

---

.github/workflows/examples.yml
.github/workflows/lint.yml

This library has already removed Optuna samplers. So no longer we don't need to test various optuna version.

Run examples with only stable optuna version

---

.github/workflows/examples.yml
README.md
cmaes/_cma.py
examples/ipop_cmaes.py
examples/quadratic_function.py
tests/test_terminate.py
tests/test_termination_criterion.py
visualizer/visualizer.py

Added `.should_stop()` method that returns `True` when CMA-ES converges to local minimum.
You can easily implement IPOP-CMA-ES and BIPOP-CMA-ES by using this method.
[Auger, A., Hansen, N.: A restart CMA evolution strategy with increasing population size. In: Proceedings of the 2005 IEEE Congress on Evolutionary Computation (CEC’2005), pp. 1769–1776 (2005a)](https://sci2s.ugr.es/sites/default/files/files/TematicWebSites/EAMHCO/contributionsCEC05/auger05ARCMA.pdf)
```python
import math
import numpy as np
from cmaes import CMA
def ackley(x1, x2):
return (
-20 * math.exp(-0.2 * math.sqrt(0.5 * (x1 ** 2 + x2 ** 2)))
- math.exp(0.5 * (math.cos(2 * math.pi * x1) + math.cos(2 * math.pi * x2)))
+ math.e + 20
)
if __name__ == "__main__":
bounds = np.array([[-32.768, 32.768], [-32.768, 32.768]]) …
```

Add should_stop() method for IPOP-CMA-ES.

---

.github/workflows/examples.yml
README.md
examples/bipop_cmaes.py
visualizer/visualizer.py

BIPOP-CMA-ES is a multi-start CMA-ES with equal budgets for two interlaced restart strategies, one with an increasing population size and one with varying small population sizes. We've already implemented termination criteria for I-POP-CMA-ES at #50. So in this pull request, I add an example of BI-POP-CMA-ES and the visualizer support.
[Hansen N. Benchmarking a BI-Population CMA-ES on the BBOB-2009 Function Testbed. In the workshop Proceedings of the Genetic and Evolutionary Computation Conference, GECCO, pages 2389–2395. ACM, 2009.](https://hal.inria.fr/inria-00382093/document)
```
$ python examples/bipop_cmaes.py 
Restart CMA-ES with popsize=12 (large)
Restart CMA-ES with popsize=11 (small)
Restart CMA-ES with popsize=24 (large)
Restart CMA-ES with popsize=21 (small)
Restart CMA-ES with …
```

Add an example of BIPOP-CMA-ES

---

.github/workflows/examples.yml
cmaes/_cma.py
examples/ellipsoid_function.py

This PR fix the coordinate of the covariance matrix.
To clarify the effect of the above fix, I've added a case where the current implementation fails.
The CMA diverges due to the lack of specification of the coordinate system.
```
evals    f(x)
======  ==========
3000  1738123.37543
6000  19991928.23666
9000  7081738487880.13770
```
With this modification, the CMA will converge properly.
```
evals    f(x)
======  ==========
3000  208462.46183
6000  37443.67228
9000  12165.74144
12000  5975.17002
15000  3067.84338
18000  1614.96333
21000   832.31420
24000   349.38618
27000   180.07809
30000    85.79394
33000    28.02802
36000     9.34316
39000     1.80444
42000     0.10396
45000     0.01673
48000     0.00037
51000     0.00000
```
Note:
This phenomenon does not appear in problems that do …

Fix coordinate rotation

---

.github/workflows/benchmarks.yml

set-env is deprecated. see https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Avoid using set-env

---

cmaes/_cma.py
cmaes/_sepcma.py

* Define `_EPS` as a module global variable instead of instance variable.
* Define `_FLT_MAX` instead of `sys.float_info.max` because 1e32 is enough.

Refactor constants definition

---

setup.cfg

Update install_requires instead of error fix because Numpy v1.20.0 drops the support of Python 3.6.

Fix mypy error at numpy v1.20.0

---

cmaes/_warm_start.py

`np.float` alias is deprecated.
https://numpy.org/devdocs/release/1.20.0-notes.html

Avoid using np.float aliases

---

cmaes/_warm_start.py
tests/test_warm_start.py

Fix dimensions of Warm starting CMA-ES

---

.github/workflows/benchmarks.yml
benchmark/optuna_solver.py
benchmark/runner.sh

We select HPO of LightGBM on Kaggle's Toxic Challenge Dataset as the benchmark problem for Warm Starting CMA-ES (See https://github.com/c-bata/benchmark-warm-starting-cmaes for more details). But this benchmark requires 5-7 days on my Macbook Pro so that it's computationally infeasible to run on GitHub Actions.
Thanks to the amazing work of kurobako by @sile, we can use RF surrogate model to overcome this problem.
1. Download kurobako v0.2.8 CLI.
1. Install Python requirements.
1. Download kurobako surrogate model.
1. Run `WARM_START=100 BUDGET=30 REPEATS=12 SURROGATE_ROOT="./surrogate-models" ./benchmark/runner.sh toxic-lightgbm ./tmp/kurobako.json`
1. `cat ./tmp/kurobako.json | kurobako plot curve --errorbar -o ./tmp`

Running benchmark of Warm Starting CMA-ES on GitHub Actions.

---

.github/workflows/tests.yml
.gitignore
cmaes/_cma.py
requirements-dev.txt
tests/test_fuzzing.py

Fix overflow errors uncovered by Coverage-guided Fuzzing.

---

cmaes/_sepcma.py
tests/test_fuzzing.py

Fuzzing for sep-CMA-ES

---

MANIFEST.in
setup.cfg

Specify `license_file` in setup.cfg (setuptools 40.8.0+).

Set license_file on setup.cfg

---

.github/workflows/tests.yml

This PR aims to support Python 3.10. Note that `3.10` must be quoted, otherwise tests are executed with Python 3.1.

Run tests with Python 3.10

---

README.md

We found some Python libraries inspired by `cmaes`. I think it would be great to introduce these libraries on README.
* Evojax
* https://github.com/google/evojax/pull/32
* evosax
* https://github.com/RobertTLange/evosax/blob/main/evosax/strategies/cma_es.py
* https://github.com/RobertTLange/evosax/blob/main/evosax/strategies/sep_cma_es.py

Introduce some related projects on README

---

.github/workflows/examples.yml
.github/workflows/tests.yml
cmaes/__init__.py
cmaes/_cmawm.py
examples/cmaes_with_margin.py
setup.cfg

The implementation of CMA-ES with margin by #115 has the following issues.
- It is implicit that discrete spaces must be located at the latter dimensions.
- The argument of `__init__` is inconsistent with `CMA`.
This PR is a continuation of #115 and changes the interface of `CMAwM` to address the issues. The example code would be changed as follows.
```python3
import numpy as np
from cmaes import CMAwM
def ellipsoid_onemax(x, n_zdim):
n = len(x)
n_rdim = n - n_zdim
r = 10
if len(x) < 2:
raise ValueError("dimension must be greater one")
ellipsoid = sum([(1000 ** (i / (n_rdim - 1)) * x[i]) ** 2 for i in range(n_rdim)])
onemax = n_zdim - (0.0 < x[(n - n_zdim) :]).sum()
return ellipsoid + r * onemax
def main():
binary_dim, continuous_dim = 10, 10
dim = binary_dim + continuous_dim
bounds = …
```

Support CMA-ES with Margin.

---

.github/workflows/examples.yml
.github/workflows/pypi-publish.yml
.github/workflows/tests.yml

Run GitHub Actions with Python 3.11.
~Let me mark this PR ready for review after merged #121 since probably scipy wheel is still not available.~
https://pypi.org/project/scipy/1.9.3/#files Scipy seems to distribute wheel packages for Python 3.11.

Support Python 3.11

---

README.md

Add a readme of CMA-ES with margin, which was introduced by https://github.com/CyberAgentAILab/cmaes/pull/121.

Add README of CMA-ES with margin

---

cmaes/_cmawm.py

`CMAwM` has much in common with `CMA` in logic.
This PR simplifies the implementation of `CMAwM` by letting `CMAwM` have `CMA` as an attribute and reusing its logic.

Reuse `CMA` inside `CMAwM`

---

cmaes/_cmawm.py

Currently, the correlation logic of out-of-range parameters of `CMAwM` is inconsistent with `CMA`: `CMAwM` repairs only parameters used for evaluation, while `CMA` also repairs parameters used for its internal logic. This might cause a problem in `CMAwM` when out-of-range parameters are sampled frequently.
This PR aligns the logic of `CMAwM` with `CMA`.
Verification script:
```python
import numpy as np
from cmaes import CMAwM
def objective(x):
return (x ** 2).sum()
def run_optimize():
n_cont = 5
bounds = np.tile([-1.0, 1.0], (n_cont + 1, 1))
steps = np.concatenate([np.zeros(n_cont), np.ones(1)])
optimizer = CMAwM(mean=np.zeros(n_cont + 1), sigma=20.0, bounds=bounds, steps=steps)
while True:
solutions = []
for _ in range(optimizer.population_size):
x_for_eval, x_for_tell = optimizer.ask() …
```

Fix correction of out-of-range continuous params of `CMAwM`

---

cmaes/_cmawm.py

A discrete version of https://github.com/CyberAgentAILab/cmaes/pull/134.

Fix correction of out-of-range discrete params of `CMAwM`

---

cmaes/_cma.py
cmaes/_cmawm.py
cmaes/_sepcma.py
cmaes/_warm_start.py

`typing.List`, `typing.Tuple`, `typing.Dict` and `typing.Set` are deprecated at Python 3.9.
https://docs.python.org/3/library/typing.html#typing.Tuple
As written in [PEP 585](https://peps.python.org/pep-0585/#implementation), we can use `list`, `tuple`, `dict`, and `set` instead, even in Python 3.7 and Python 3.8.

Avoid to use `typing.List`, `typing.Dict`, and `typing.Tuple`.

---

cmaes/_cmawm.py

Check the feasibility of all parameters instead of only continuous ones.
ref: https://github.com/CyberAgentAILab/cmaes/pull/136

Check feasibility of sampled discrete parameters in `CMAwM`

---

cmaes/_cmawm.py

For flexible use in other libraries such as Optuna, this PR allows input of no discrete spaces for `CMAwM` (should behave the same as `CMA` in that case).
Dependent on https://github.com/CyberAgentAILab/cmaes/pull/141.

Allow no discrete spaces in `CMAwM`

---

cmaes/_cmawm.py

Remove warnings since CMAwM can accept the search space that has no discrete params.

Remove warnings in CMAwM class

---

cmaes/_cmawm.py

I observed a performance degradation from https://github.com/CyberAgentAILab/cmaes/pull/121#issuecomment-1296691448 in Optuna on HPO-bench: 
(_CmaEsSampler_0_NopPruner: `CMA`, _CmaEsSampler_1_NopPruner: `CMAwM`)
I found out that this is caused by https://github.com/CyberAgentAILab/cmaes/pull/136 and https://github.com/CyberAgentAILab/cmaes/pull/140, which repair out-of-range discrete parameters in the same way as continuous parameters.
I'm not sure why this hurt the performance this much, but let me revert these changes for now. I confirmed that this PR brings the performance back to a similar level as the original:

Revert handling of infeasible discrete parameters

---

README.md
examples/bipop_cmaes.py

The current example does not reset the initial sigma when the restart with a 'small' population size is performed.
This PR fixes this problem.

fix sigma setting

---

tools/cmaes_visualizer.py

This PR fixes the bug of BIPOP-CMA-ES in the visualization tool.

fix BIPOP-CMA in visualization

---

cmaes/_cma.py

The current behavior : the assertion fails when lr_adapt=True and sigma is an integer (like sigma=1) which forces to put sigma = 1.0
With `assert isinstance(old_sigma, (int, float))` we allow integer values for sigma

fix the old_sigma assertion when lr_adapt=True

---

README.md

https://www.kubeflow.org/docs/components/katib/katib-config/ is broken, so this PR replaces it to the new url.

Fix the broken link to Katib documentation

---

README.md
cmaes/__init__.py
cmaes/_mapcma.py
examples/mapcma.py

I have implemented MAP-CMA [Hamano+, PPSN2024] and created the description for the README.
Note that in the README, the abbreviation of the reference [Hamano et al. 2024] has been changed to distinguish between GECCO2024 and PPSN2024.

MAP-CMA (PPSN2024)

---

.github/workflows/tests.yml
tests/test_free_threaded.py

- Added a test using a Python 3.13t environment with experimental free-threading support
- Added a test to run simple CMA-based optimization tests in parallel using `pytest-freethreaded`

Add tests for free-threaded python

---

cmaes/_cma.py
tests/test_fuzzing.py

At the moment, cmaes does not support 1D search space.
However, based on my understanding, the CMA-ES algorithm can naturally handle 1D search space, so I want to support it.
It has also been observed that some users want to support this (https://github.com/optuna/optuna/discussions/5524).
In this PR, I support 1D search space in CMA-ES.
- Change an assertion in `_cma.py` to ensure `n_dim > 0` rather than `n_dim > 1`.
I confirmed that the code with the above change passes all tests and works fine in the following toy example.
```python
import numpy as np
from cmaes import CMA
def quadratic(x1):
return (x1 - 3) ** 2
if __name__ == "__main__":
optimizer = CMA(mean=np.zeros(1), sigma=1.3)
for generation in range(20):
solutions = []
for _ in range(optimizer.population_size):
x = …
```

[Proposal] Support 1D search space in CMA-ES

---

cmaes/_cma.py

Although there were no mypy type errors before, with Python 3.13.2 a mypy type error has appeared in the workflow tests. This change keeps the fix minimal and avoids unnecessary modifications.

Fix mypy type error in workflow

---

cmaes/_cmawm.py

I have modified the discretization process and the margin correction of CMA-ESwM.
There was a problem where the continuous value before discretization was not encoded into the correct discrete variable when it matched a discretization threshold. This problem occurred when the probability distribution extremely converged, but in some cases, a discrete variable outside the domain could be generated.
The code has been modified so that the processing when the continuous value before discretization matches the discretization threshold follows the definition in the CMA-ESwM paper [Hamano+, GECCO2022]. In other cases, the behavior of the algorithm after the changes is consistent with its behavior before the changes.

fix the discretization process of CMA-ESwM

---

tools/cmaes_visualizer.py
tools/ws_cmaes_visualizer.py

This pull request addresses flake8 F824 errors that have emerged in the workflow tests when running with Python 3.13.2.
The errors are caused by unnecessary global declarations in functions where the variables are not reassigned.
No changes to the actual behavior of the code.

Remove unnecessary 'global' declarations causing flake8 F824 errors

---

.github/workflows/examples.yml
README.md
cmaes/cmasop.py
examples/cma_sop.py
requirements-dev.txt

This is the implementation of CMA-ES-SoP [Uchida+, PPSN 2024].
https://arxiv.org/abs/2408.13046

CMA-ES-SoP (PPSN 2024)
